Name:
  type: Short Text
Height:
  type: Real
Weight:
  type: Real
Description:
  type: Case Insensitive Text
Category:
  type: Short Text
Abilities:
  type: Short Text
National Pokedex number:
  type: Integer
Caught:
  type: Boolean
test:
  type: Boolean
