GitHub issue:
  type: Text
Signs and Symptoms:
  type: Text
Treatments:
  type: Text
Fix Difficulty:
  type: Integer
Pull Leech Logs:
  type: Boolean
Last Updated:
  type: Date Time
Versions Affected:
  type: semver-range
Fixed in Version:
  type: semver
Address already in use:
  type: Text
TEST FIELD:
  type: Time
DATE:
  type: Date
